language: python
addons:
  homebrew:
    packages:
      gobject-introspection
jobs:
  include:
   # Mac OS
    - os: macos
      language: shell
before_install:
  - export PY=python3
  - export PIP=pip3
  - choco install python --version 3.8.8
  - $PY --version # show Python version
  - $PIP install -U pip # update pip itself
  - export VIRT_ROOT=/home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION
  - export PKG_CONFIG_PATH=$VIRT_ROOT/lib/pkgconfig
install:
 # - sudo apt-get install gir1.2-gtk-3.0 gir1.2-notify-0.7 libgirepository1.0-dev libxml2-utils
  - $PIP install PyGObject
# coveralls.io
  - $PIP install coveralls requests[security]
# install mock
  - $PIP install mock
script:
# Make the same file as on AppVeyor, so coveralls does not complain.
   - echo "revision = \"`git rev-parse --short HEAD `\"" >bleachbit/Revision.py
   - echo "build_number = \"$TRAVIS_BUILD_NUMBER" >>bleachbit/Revision.py
# Run tests.
   - make tests COVERAGE="coverage run --include='bleachbit/*'"
after_success:
   - mv .coverage .coverage.travis
   - sudo $PIP install appveyor-artifacts
   - appveyor-artifacts -o az0 -n bleachbit -m -c $TRAVIS_COMMIT download
   - coverage combine
   - coverage report
   - coveralls
